#!/bin/bash

echo "🚀 COLLEGE CLIMB - DEPLOY TO PRODUCTION"
echo "========================================"
echo ""
echo "Step 1: Install Vercel CLI"
echo "Run: npm install -g vercel"
echo ""
echo "Step 2: Login to Vercel"
echo "Run: vercel login"
echo ""
echo "Step 3: Deploy"
echo "Run: vercel --prod"
echo ""
echo "Step 4: Set Environment Variables in Vercel Dashboard"
echo "Go to: https://vercel.com/[your-project]/settings/environment-variables"
echo "Add: OPENAI_API_KEY = [your key]"
echo "Add: All NEXT_PUBLIC_FIREBASE_* variables from .env"
echo ""
echo "That's it! Your app will be live at: https://your-project.vercel.app"
echo ""
echo "========================================"
echo ""
echo "💡 Want me to do it? Run these commands:"
echo ""
echo "npm install -g vercel"
echo "vercel login"
echo "vercel --prod"
